services:

  partytide-db:
    image: mariadb:10.6
    container_name: partytide-db
    env_file:
      - .env
    volumes:
      - partytide-db-data:/var/lib/mysql
      - ./Database:/ace/Database
      - ./Scripts/initdb.sh:/docker-entrypoint-initdb.d/1.sh
      - ./Database/Optional/World/ACE-World-Database-v0.9.250.sql.gz:/docker-entrypoint-initdb.d/2.sql.gz
    ports:
      - "127.0.0.1:3306:3306/tcp"
    restart: on-failure:3
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  partytide-server:
    build: .
    image: acemulator/ace:latest
    depends_on:
      - partytide-db
    container_name: partytide-server
    env_file:
      - .env
    volumes:
      - ./Dats:/ace/Dats
      - ./Content:/ace/Content
      - ./Config:/ace/Config
      - ./Partytide-Content:/ace/Partytide-Content
      - ./Logs:/ace/Logs
    ports:
      - "127.0.0.1:9000-9001:9000-9001/udp"
    restart: on-failure:3

volumes:
  partytide-db-data:
